version: '3'
services:
  torpedo-mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./datadir:/data/db
  torpedo:
    links:
      - torpedo-mongo
    image: "tb0hdan/torpedo:1.0.50"
    depends_on:
      - torpedo-mongo
    env_file: ./env.list
    restart: unless-stopped
    environment:
      - MONGO=torpedo-mongo
